### PR TITLE
ROS Node for Feature Tracking

### PR DESCRIPTION
**Pull request by foehnx**
> This is still a draft and not ready for review or deployment.

This pull request will provide a ROS node wrapping the provided feature tracker.
It aims at simple deployment in a ROS environment on CUDA-supported platforms.

@berndpfrommer feel free to take a look, review, or even test if you like.

### CODE REVIEW

**Comment by berndpfrommer** [comment]
Some recommendations about structuring:
1) Any ROS stuff should be in a separate package. Do not commingle ROS with vilib even if ROS is not required to build the package. There may be users out there that don't want to use ROS, or actually use ROS2
2) The custom msgs should be further broken out into a separate ROS package. This is recommended ROS practice, see e.g.:
http://docs.ros.org/en/melodic/api/catkin/html/howto/format2/building_msgs.html
3) As if there weren't enough packages already, I would suggest to create a catkin wrapper package, much like I created an ament wrapper package here: https://github.com/berndpfrommer/vilib_ament 
This wrapper package in turn builds and exports the vilib package into the catkin framework. This way vilib can stay a plain cmake project, and catkin is happy because it can find and build the package in the usual manner.
Writing the catkin wrapper package can be tricky and a time sink. If you are willing to go that route (but only then!) I volunteer to write one.

So here is the package structure I would recommend:

- vilib_msgs  (ROS package with messages only)
- vilib_catkin (ROS catkin package that exports vilib)
    - under here lives the plain cmake vilib package
- vilib_feature_tracking (ROS package that has your tracking code, and requires vilib_msgs and vilib_catkin)

**Comment by berndpfrommer** [comment]
I tried a naive catkin build on the present PR but it didn't get very far. This is on ubuntu 20.04/ROS noetic.

```
Starting  >>> catkin_simple                                                                                                                                                                                        
Finished  <<< catkin_simple                [ 0.2 seconds ]                                                                                                                                                         
Starting  >>> vilib                                                                                                                                                                                                
__________________________________________________________________________________________________________________________________________________________________________________________________________________ 
Errors     << vilib:make /home/pfrommer/Documents/vilib/logs/vilib/build.make.002.log                                                                                                                              
c++: error: per-thread: No such file or directory                                                                                                                                                                  
c++: error: per-thread: No such file or directory                                                                                                                                                                  
c++: error: per-thread: No such file or directory                                                                                                                                                                  
c++: error: per-thread: No such file or directory                                                                                                                                                                  
nvcc fatal   : Value '-Wfatal-errors' is not defined for option 'Werror'                                                                                                                                           
c++: error: unrecognized command line option ‘--device-w’                                                                                                                                                          
c++: error: unrecognized command line option ‘--device-w’                                                                                                                                                          
c++: error: unrecognized command line option ‘--device-w’                                                                                                                                                          
c++: error: per-thread: No such file or directory                                                                                                                                                                  
c++: error: per-thread: No such file or directory                                                                                                                                                                  
c++: error: per-thread: No such file or directory                                                                                                                                                                  
c++: error: unrecognized command line option ‘--ftz=true’                                                                                                                                                          
make[2]: *** [CMakeFiles/vilib.dir/build.make:141: CMakeFiles/vilib.dir/home/pfrommer/Documents/vilib/src/vilib/visual_lib/src/feature_detection/detector_base_gpu_cuda_tools.cu.o] Error 1                        
make[2]: *** Waiting for unfinished jobs....                                                                                                                                                                       
nvcc fatal   : Value '-Wfatal-errors' is not defined for option 'Werror'      
```

**Comment by foehnx** [comment]
@berndpfrommer thanks for the feedback.
The compile issues should be fixed now.
I started to split the ros package into multiple ones following your recommendation.
However, so far I'm only able to separate the message generation.
I can't cmake it in a way that both CUDA and catkin correctly handle a standalone `vilib_catkin` build, which I could then link from `vilib_tracker`.
Any suggestions how to approach this?

**Comment by berndpfrommer** [comment]
Let me see if I can put something together by end of today.

**Comment by foehnx** [comment]
@berndpfrommer never mind. got it. will test further now.

**Comment by berndpfrommer** [comment]
Didn't see your reply until now. In the meanwhile I put together this:

https://github.com/berndpfrommer/vilib_packages

Each of the three subdirectories should be separate repos, in particular the msgs.
Note: you can find the catkin wrapper scheme in many ETHZ packages.

**Comment by foehnx** [comment]
thanks a lot for the help.
however, to keep things simple I don't want to split the repository up!
So the individual packages will stay here, while the repository can still be used without ROS as before.

**Pull request merged**
